# Generated by Django 2.2.1 on 2019-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190510_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('times', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
